fix multiplicity_cut() function
smash-transport/sparkx pull request #296
Opened 2024-10-24 14:34 UTC by LucasConstantin

This closes issue #294.  `Oscar.multiplicity_cut()` now takes a tuple and the `update_num_output_per_event_after_filter()' now correctly updates the new num_output_per_event. I also add the case that the number of events is zero in the `print_particle_lists_to_file()` function.

2024-10-24 14:54 UTC, NGoetz commented
The tests are failing, apparently the changes broke things. I will review once they pass.

2024-10-24 15:52 UTC, NGoetz commented
In general it is advisable to actually run the tests before pushing.

2024-10-25 14:11 UTC, NGoetz requested changes
While your changes generally fix the underlying issue, I think you should work a bit more carefully and also try to understand the logic  of the codebase you are editing.

2024-10-25 14:11 UTC, NGoetz commented on src/sparkx/Oscar.py
> +            if self.num_events_ == 0:
You were reporting issues with the case that there are no events left - is a warning sufficient to deal with this? 
Also, such changes have to be done always for both oscar and Jetscape. You would have easily noticed that running the tests just once.

2024-10-25 14:11 UTC, NGoetz commented on tests/test_Filter.py
This file lacks

- [ ] A test for the case that no events are left
- [ ] A test for the warning

Every feature or warning or error that is added has to be covered in tests!

2024-10-25 14:11 UTC, NGoetz commented on src/sparkx/Filter.py
> +    Apply multiplicity cut. Remove all events with a multiplicity not coplying
Please use spell checkers. Or Github Copilot.

2024-11-06 13:11 UTC, NGoetz commented
@LucasConstantin please take a look at the required changes.

2024-11-07 14:58 UTC, NGoetz commented
@Hendrik1704 do you understand why the checks are not running for this PR?

2024-11-07 15:33 UTC, NGoetz commented
@LucasConstantin can you please try to rebase on sparkx_devel tomorrow or on Monday? Reviewing only makes sense once the Actions succeed.

2024-11-11 15:19 UTC, NGoetz requested changes
Very good, and congrats for your first successful rebase! I have a minor error-handling request. On the top you can see the reason for your action fail:
`src/sparkx/BaseStorer.py:851: error: Need type annotation for "updated_num_output_per_event"  [var-annotated]`
You forgot the type of ` updated_num_output_per_event`

2024-11-11 15:19 UTC, NGoetz commented on src/sparkx/Oscar.py
> +                warnings.warn("The number of events is zero.")
I think we should be consistent between Jetscape, where you have an error, and Oscar, where you warn. I think a warning is the more reasonable choice. Such things can happen on purpose.

2024-11-11 15:19 UTC, NGoetz commented on tests/test_Oscar.py
> +def test_empty_oscar_print(tmp_path, output_path):
Implement the same test for Jetscape, too

2024-11-11 15:22 UTC, Hendrik1704 commented
@LucasConstantin The static typing action failed for this function: `updated_num_output_per_event` in BaseStorer
Please check if all the data types are given there.

2024-11-18 08:28 UTC, NGoetz approved these changes
Looks good, thank you!

2024-11-18 08:28 UTC, merged